### PR TITLE
Create dl-cores.sh

### PR DESCRIPTION
**Pull request by meleu**
a script to download all cores supported by RALibretro

### CODE REVIEW

**Comment by leiradel** [comment]
Cool! Is `wget` available by default on MSYS2? If not, I think it'll be good to add a note about it in the help. If we can automatically determine `wget`'s availability it would be even better.

**Comment by meleu** [comment]
oh sorry!!! I have to deal with this dependency!! it was on my ToDo list for this script but this ToDo list was just on my mind... :sweat_smile: 
I'll deal with it and submit another PR.

**Comment by leiradel** [comment]
Just commit the changes and they will end up here in this PR.

**Comment by meleu** [comment]
that's what I meant :P

**Comment by meleu** [comment]
@leiradel as you requested, the script now checks the dependencies and do NOT create a logfile by default.

the command to install every supported core is `./dl-cores.sh all`. ;-)

**Comment by leiradel** [comment]
Thanks

**Pull request merged**
